import type { Character } from '../types';
import type { CombatantDefinition, CombatStyle } from './pentagram-combat';

export type FighterKitEvidence = 'onscreen' | 'motif' | 'simulation';

export interface FighterProfile {
  id: string;
  style: string;
  archetype: string;
  combatStyle: CombatStyle;
  evidence: FighterKitEvidence;
  power: number;
  range: number;
  speed: number;
  guard: number;
  tensionGain: number;
  basicMove: string;
  heavyMove: string;
  specialMove: string;
}

export const FIGHTER_KIT_EVIDENCE_LABELS: Readonly<Record<FighterKitEvidence, string>> = {
  onscreen: 'Screen-inspired Simulation kit',
  motif: 'Character-motif Simulation kit',
  simulation: 'Limited-evidence Simulation kit',
};

export const FIGHTER_PROFILES: Readonly<Record<string, FighterProfile>> = {
  charlie: {
    id: 'charlie',
    style: 'Hope all-rounder',
    archetype: 'Balanced morale pressure',
    combatStyle: 'balanced',
    evidence: 'onscreen',
    power: 11,
    range: 58,
    speed: 68,
    guard: 64,
    tensionGain: 16,
    basicMove: 'Royal jab',
    heavyMove: 'Morningstar sweep',
    specialMove: 'Morningstar rally',
  },
  vaggie: {
    id: 'vaggie',
    style: 'Discipline duelist',
    archetype: 'Counter-hit security',
    combatStyle: 'duelist',
    evidence: 'onscreen',
    power: 13,
    range: 68,
    speed: 72,
    guard: 78,
    tensionGain: 14,
    basicMove: 'Spear thrust',
    heavyMove: 'Spear-breaker arc',
    specialMove: 'Guardian intercept',
  },
  angeldust: {
    id: 'angeldust',
    style: 'Acrobat pressure',
    archetype: 'Multi-angle trickster',
    combatStyle: 'trickster',
    evidence: 'onscreen',
    power: 13,
    range: 74,
    speed: 80,
    guard: 44,
    tensionGain: 18,
    basicMove: 'Acrobat jab',
    heavyMove: 'Crossfire sweep',
    specialMove: 'Multi-angle barrage',
  },
  alastor: {
    id: 'alastor',
    style: 'Radio controller',
    archetype: 'Space-control boss',
    combatStyle: 'boss',
    evidence: 'onscreen',
    power: 17,
    range: 92,
    speed: 54,
    guard: 72,
    tensionGain: 12,
    basicMove: 'Static cane snap',
    heavyMove: 'Shadow sweep',
    specialMove: 'Dead air',
  },
  husk: {
    id: 'husk',
    style: 'Gambler counterplay',
    archetype: 'Read-heavy trickster',
    combatStyle: 'trickster',
    evidence: 'onscreen',
    power: 12,
    range: 62,
    speed: 58,
    guard: 70,
    tensionGain: 17,
    basicMove: 'Card toss',
    heavyMove: 'Wing rake',
    specialMove: 'Loaded deck',
  },
  niffty: {
    id: 'niffty',
    style: 'Tiny blender',
    archetype: 'High-speed rushdown',
    combatStyle: 'rushdown',
    evidence: 'onscreen',
    power: 9,
    range: 36,
    speed: 94,
    guard: 38,
    tensionGain: 20,
    basicMove: 'Cleaning dash',
    heavyMove: 'Broom spin',
    specialMove: 'Spotless frenzy',
  },
  sirpentious: {
    id: 'sirpentious',
    style: 'Gadget setplay',
    archetype: 'Inventor zoner',
    combatStyle: 'zoner',
    evidence: 'onscreen',
    power: 12,
    range: 72,
    speed: 44,
    guard: 58,
    tensionGain: 15,
    basicMove: 'Coil poke',
    heavyMove: 'Clockwork launcher',
    specialMove: 'Egg Boiz barrage',
  },
  lucifer: {
    id: 'lucifer',
    style: 'Royal trickster',
    archetype: 'Transforming boss pressure',
    combatStyle: 'boss',
    evidence: 'onscreen',
    power: 18,
    range: 82,
    speed: 76,
    guard: 82,
    tensionGain: 13,
    basicMove: 'Cane flourish',
    heavyMove: 'Winged feint',
    specialMove: 'Royal showstopper',
  },
  cherribomb: {
    id: 'cherribomb',
    style: 'Explosive zoner',
    archetype: 'Volatile space denial',
    combatStyle: 'zoner',
    evidence: 'onscreen',
    power: 14,
    range: 86,
    speed: 66,
    guard: 48,
    tensionGain: 17,
    basicMove: 'Fuse kick',
    heavyMove: 'Bomb arc',
    specialMove: 'Cluster barrage',
  },
  vox: {
    id: 'vox',
    style: 'Signal zoner',
    archetype: 'Network space control',
    combatStyle: 'zoner',
    evidence: 'motif',
    power: 16,
    range: 90,
    speed: 58,
    guard: 68,
    tensionGain: 13,
    basicMove: 'Static jab',
    heavyMove: 'Signal line',
    specialMove: 'Network overload',
  },
  valentino: {
    id: 'valentino',
    style: 'Volatile bruiser',
    archetype: 'Long-reach pressure',
    combatStyle: 'bruiser',
    evidence: 'motif',
    power: 16,
    range: 76,
    speed: 48,
    guard: 66,
    tensionGain: 12,
    basicMove: 'Long-reach swipe',
    heavyMove: 'Volatile rush',
    specialMove: 'Studio pressure',
  },
  velvette: {
    id: 'velvette',
    style: 'Runway trickster',
    archetype: 'Fast feint pressure',
    combatStyle: 'trickster',
    evidence: 'motif',
    power: 13,
    range: 58,
    speed: 84,
    guard: 50,
    tensionGain: 19,
    basicMove: 'Runway feint',
    heavyMove: 'Trend breaker',
    specialMove: 'Viral momentum',
  },
  adam: {
    id: 'adam',
    style: 'Exorcist boss',
    archetype: 'Armored celestial bruiser',
    combatStyle: 'boss',
    evidence: 'onscreen',
    power: 18,
    range: 84,
    speed: 62,
    guard: 76,
    tensionGain: 11,
    basicMove: 'Weapon chop',
    heavyMove: 'Light burst',
    specialMove: 'Exorcist assault',
  },
  emily: {
    id: 'emily',
    style: 'Hope guardian',
    archetype: 'Defensive all-rounder',
    combatStyle: 'guardian',
    evidence: 'simulation',
    power: 10,
    range: 56,
    speed: 70,
    guard: 78,
    tensionGain: 18,
    basicMove: 'Light step',
    heavyMove: 'Seraph ward',
    specialMove: 'Hopeful resolve',
  },
  sera: {
    id: 'sera',
    style: 'High Seraph guardian',
    archetype: 'Defensive authority',
    combatStyle: 'guardian',
    evidence: 'simulation',
    power: 14,
    range: 78,
    speed: 48,
    guard: 88,
    tensionGain: 12,
    basicMove: 'Celestial ward',
    heavyMove: 'Authority push',
    specialMove: 'High Seraph stand',
  },
  lute: {
    id: 'lute',
    style: 'Exorcist duelist',
    archetype: 'Relentless spear pressure',
    combatStyle: 'duelist',
    evidence: 'onscreen',
    power: 15,
    range: 72,
    speed: 82,
    guard: 68,
    tensionGain: 15,
    basicMove: 'Exorcist slash',
    heavyMove: 'Wing dive',
    specialMove: 'Lieutenant assault',
  },
  carmilla: {
    id: 'carmilla',
    style: 'Carmine footsies',
    archetype: 'Precision counter-duelist',
    combatStyle: 'duelist',
    evidence: 'onscreen',
    power: 16,
    range: 72,
    speed: 78,
    guard: 82,
    tensionGain: 14,
    basicMove: 'Precision kick',
    heavyMove: 'Carmine heel',
    specialMove: 'Protective counterdance',
  },
  rosie: {
    id: 'rosie',
    style: 'Poised all-rounder',
    archetype: 'Commanding morale control',
    combatStyle: 'balanced',
    evidence: 'simulation',
    power: 14,
    range: 64,
    speed: 62,
    guard: 72,
    tensionGain: 17,
    basicMove: 'Etiquette jab',
    heavyMove: 'Poised sweep',
    specialMove: 'Overlord rally',
  },
  zestial: {
    id: 'zestial',
    style: 'Ancient controller',
    archetype: 'Slow space denial',
    combatStyle: 'zoner',
    evidence: 'simulation',
    power: 17,
    range: 88,
    speed: 36,
    guard: 84,
    tensionGain: 11,
    basicMove: 'Measured reach',
    heavyMove: 'Ancient guard',
    specialMove: 'Overlord presence',
  },
  zeezi: {
    id: 'zeezi',
    style: 'Powerholder bruiser',
    archetype: 'Heavy-body momentum',
    combatStyle: 'bruiser',
    evidence: 'simulation',
    power: 16,
    range: 54,
    speed: 38,
    guard: 80,
    tensionGain: 13,
    basicMove: 'Heavy jab',
    heavyMove: 'Overlord stomp',
    specialMove: 'Powerholder crash',
  },
  baxter: {
    id: 'baxter',
    style: 'Science setplay',
    archetype: 'Experimental projectile control',
    combatStyle: 'zoner',
    evidence: 'motif',
    power: 11,
    range: 78,
    speed: 50,
    guard: 54,
    tensionGain: 16,
    basicMove: 'Volt probe',
    heavyMove: 'Pressure pulse',
    specialMove: 'Tank discharge',
  },
  abel: {
    id: 'abel',
    style: 'Celestial training kit',
    archetype: 'Neutral limited-evidence fighter',
    combatStyle: 'balanced',
    evidence: 'simulation',
    power: 10,
    range: 56,
    speed: 60,
    guard: 60,
    tensionGain: 15,
    basicMove: 'Celestial jab',
    heavyMove: 'Halo sweep',
    specialMove: 'Training radiance',
  },
  sim_applicant_marlow: {
    id: 'sim_applicant_marlow',
    style: 'Defensive footsies',
    archetype: 'Starter-safe guardian',
    combatStyle: 'guardian',
    evidence: 'simulation',
    power: 11,
    range: 52,
    speed: 52,
    guard: 68,
    tensionGain: 14,
    basicMove: 'Glass-step strike',
    heavyMove: 'Mirror shoulder',
    specialMove: 'Composure break',
  },
  sim_applicant_ember: {
    id: 'sim_applicant_ember',
    style: 'Flare rush',
    archetype: 'Momentum trainee',
    combatStyle: 'rushdown',
    evidence: 'simulation',
    power: 11,
    range: 50,
    speed: 72,
    guard: 48,
    tensionGain: 19,
    basicMove: 'Spark lunge',
    heavyMove: 'Flashpoint hook',
    specialMove: 'Cinder burst',
  },
};

const HAZBIN_DIRECTORY_PROFILE_CACHE = new Map<string, FighterProfile>();

function getHazbinDirectoryFighterProfile(fighter: Character): FighterProfile | undefined {
  if (!fighter.id.startsWith('hz_')) return undefined;

  const cached = HAZBIN_DIRECTORY_PROFILE_CACHE.get(fighter.id);
  if (cached) return cached;

  const riskPower: Readonly<Record<Character['riskLevel'], number>> = {
    low: 9,
    medium: 11,
    high: 13,
    catastrophic: 15,
  };
  const riskGuard: Readonly<Record<Character['riskLevel'], number>> = {
    low: 56,
    medium: 60,
    high: 66,
    catastrophic: 72,
  };
  const profile: FighterProfile = {
    id: fighter.id,
    style: 'Simulation AU fundamentals',
    archetype: 'Limited-evidence training all-rounder',
    combatStyle: 'balanced',
    evidence: 'simulation',
    power: riskPower[fighter.riskLevel],
    range: 56,
    speed: 60,
    guard: riskGuard[fighter.riskLevel],
    tensionGain: 15,
    basicMove: 'Training jab',
    heavyMove: 'Training sweep',
    specialMove: 'Simulation drive',
  };
  HAZBIN_DIRECTORY_PROFILE_CACHE.set(fighter.id, profile);
  return profile;
}

export function getFighterProfile(fighter: Character | undefined): FighterProfile | undefined {
  if (!fighter) return undefined;
  return FIGHTER_PROFILES[fighter.id] ?? getHazbinDirectoryFighterProfile(fighter);
}

export function buildCombatantDefinition(
  fighter: Character,
  profile: FighterProfile,
): CombatantDefinition {
  return {
    name: fighter.name,
    power: profile.power,
    range: profile.range,
    speed: profile.speed,
    guard: profile.guard,
    tensionGain: profile.tensionGain,
    basicMove: profile.basicMove,
    heavyMove: profile.heavyMove,
    specialMove: profile.specialMove,
    style: profile.combatStyle,
  };
}
