import { DatabaseState, Character, Room, Faction, Relationship, LoreEntry, ResourceLedger, StaffTask, RehabilitationPlan, RehabilitationSession, Incident, ReputationState, TimelineState, AuditLog, AppSettings } from '../types';

export function getSeedData(): DatabaseState {
  const characters: Character[] = [
    {
      id: 'charlie',
      name: 'Charlie Morningstar',
      alias: 'Princess of Hell',
      type: 'hellborn',
      rank: 'royalty',
      role: 'founder',
      status: 'staff',
      riskLevel: 'low',
      charlieTrust: 100,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Operational founder profile. Trust, risk and hotel-role fields are simulation values, not canon measurements.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E01',
      spoilerLevel: 'none',
      description: 'Hellborn princess of Hell and founder of the hotel project, seeking to prove that sinners can be redeemed.'
    },
    {
      id: 'vaggie',
      name: 'Vaggie',
      alias: 'Manager V',
      type: 'angel',
      rank: 'former_exorcist',
      role: 'manager',
      status: 'staff',
      riskLevel: 'low',
      charlieTrust: 100,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Handles logistics and physical security. Protective of Charlie. Tactical background. High vigilance against external threats.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E01, S1E06',
      spoilerLevel: 'season_1', // spoiler: angel background
      description: 'The operations manager and head of security at the hotel, focused on structural discipline and defensive safety.'
    },
    {
      id: 'angeldust',
      name: 'Angel Dust',
      alias: 'Angel',
      type: 'sinner',
      rank: 'none',
      role: 'resident',
      status: 'resident',
      riskLevel: 'high',
      charlieTrust: 45,
      rehabProgress: 20,
      rehabTracked: true,
      operationalDataStatus: 'simulation_au',
      contracts: ['Soul contract with Valentino (studio-bound terms)'],
      notes: 'First official resident. High relapsing rate due to external employment pressures and emotional instability. Needs constant supervision.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E01',
      spoilerLevel: 'none',
      description: 'A prominent hotel resident dealing with external soul contracts, substance dependency, and complex rehabilitation requirements.'
    },
    {
      id: 'alastor',
      name: 'Alastor',
      alias: 'The Radio Demon',
      type: 'sinner',
      rank: 'overlord',
      role: 'sponsor',
      status: 'staff',
      riskLevel: 'catastrophic',
      charlieTrust: 30,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'A powerful Overlord assisting the hotel for his own reasons. Any later constraints on him belong in spoiler-scoped codex records.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E01',
      spoilerLevel: 'none',
      description: 'A notorious media-oriented Overlord acting as the hotel\'s patron, offering defense and assistance while maintaining personal agendas.'
    },
    {
      id: 'husk',
      name: 'Husk',
      alias: 'Husker',
      type: 'sinner',
      rank: 'former_overlord',
      role: 'bartender',
      status: 'staff',
      riskLevel: 'medium',
      charlieTrust: 75,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: ['Soul bound by Alastor\'s contract'],
      notes: 'Assigned by Alastor as bartender. Cynical but observant. Valuable for reading resident temperaments and de-escalation at the bar.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E04',
      spoilerLevel: 'season_1',
      description: 'An experienced former Overlord now acting as the hotel bartender and front-line counselor for distressed residents.'
    },
    {
      id: 'niffty',
      name: 'Niffty',
      alias: 'Clean Demon',
      type: 'sinner',
      rank: 'none',
      role: 'housekeeper',
      status: 'staff',
      riskLevel: 'low',
      charlieTrust: 80,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Alastor summons Niffty to help at the hotel, but the series does not confirm that he owns her soul or holds a contract over her.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E01',
      spoilerLevel: 'none',
      description: 'The energetic housekeeper of the facility, managing sanitary conditions and structural pest control.'
    },
    {
      id: 'sirpentious',
      name: 'Sir Pentious',
      alias: 'The Snake',
      type: 'sinner',
      rank: 'none',
      role: 'resident',
      status: 'applicant',
      riskLevel: 'medium',
      charlieTrust: 15,
      rehabProgress: 10,
      rehabTracked: true,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Initially an antagonist deploying clockwork warmachines. Possesses technical expertise. Confirmed to transition status under Season 1 progress.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E02, S1E08',
      spoilerLevel: 'season_1',
      description: 'An inventor and sinner who joins the hotel during Season 1; his finale outcome is projected by the selected timeline.',
      timelineStates: {
        pilot_legacy: { role: 'antagonist', status: 'external', riskLevel: 'medium', rehabProgress: 0, rehabTracked: false },
        season_1_start: { type: 'sinner', role: 'resident', status: 'applicant', riskLevel: 'medium', rehabProgress: 10, rehabTracked: true },
        season_1_end: { type: 'redeemed_soul', role: 'external', status: 'redeemed', riskLevel: 'low', rehabProgress: 100, rehabTracked: false },
        season_2: { type: 'redeemed_soul', role: 'external', status: 'redeemed', riskLevel: 'low', rehabProgress: 100, rehabTracked: false }
      }
    },
    {
      id: 'lucifer',
      name: 'Lucifer Morningstar',
      alias: 'King of Hell',
      type: 'fallen_angel',
      rank: 'royalty',
      role: 'external',
      status: 'external',
      riskLevel: 'catastrophic',
      charlieTrust: 90,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Charlie\'s father. Suffering from long-term clinical isolation and political apathy. Holds ultimate authority in the realm. Potential major ally.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E05',
      spoilerLevel: 'season_1',
      description: 'The ruler of Hell and Charlie\'s father, whose political influence and celestial status offer significant protection to the hotel.'
    },
    {
      id: 'cherribomb',
      name: 'Cherri Bomb',
      alias: 'Bomb Queen',
      type: 'sinner',
      rank: 'none',
      role: 'ally',
      status: 'external',
      riskLevel: 'high',
      charlieTrust: 50,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Close associate of Angel Dust. Highly destructive combat preferences. Responds poorly to structure, but defends residents in crises.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E06',
      spoilerLevel: 'season_1',
      description: 'A chaotic sinner specialized in explosives and turf wars, acting as an external defender of the hotel\'s residents.'
    },
    {
      id: 'vox',
      name: 'Vox',
      alias: 'The TV Demon',
      type: 'sinner',
      rank: 'overlord',
      role: 'antagonist',
      status: 'banned',
      riskLevel: 'catastrophic',
      charlieTrust: 0,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Leader of the Vees. Employs electronic surveillance and propaganda. Actively seeks to discredit the hotel to maintain sinner control.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E02',
      spoilerLevel: 'none',
      description: 'A media and technology Overlord who coordinates digital broadcasts and hostile public relations campaigns against the hotel.'
    },
    {
      id: 'valentino',
      name: 'Valentino',
      alias: 'Val',
      type: 'sinner',
      rank: 'overlord',
      role: 'antagonist',
      status: 'banned',
      riskLevel: 'catastrophic',
      charlieTrust: 0,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: ['Holds contract on Angel Dust\'s external labor'],
      notes: 'Controls adult entertainment studio. Highly abusive and volatile. Poses severe threat to Angel Dust\'s mental stability.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E02',
      spoilerLevel: 'none',
      description: 'A powerful and volatile Overlord controlling entertainment contracts, acting as a major antagonist to resident rehabilitation.'
    },
    {
      id: 'velvette',
      name: 'Velvette',
      alias: 'Fashion Vee',
      type: 'sinner',
      rank: 'overlord',
      role: 'antagonist',
      status: 'banned',
      riskLevel: 'high',
      charlieTrust: 10,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Designs fashion trends. Handles public relations and social media campaigns for the Vees. Vocal opponent of the hotel\'s ideals.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E02',
      spoilerLevel: 'none',
      description: 'An Overlord managing social media trends and fashion, utilizing influencer status to coordinate marketing against the hotel.'
    },
    {
      id: 'adam',
      name: 'Adam',
      alias: 'The First Man',
      type: 'angel',
      rank: 'exorcist_commander',
      role: 'antagonist',
      status: 'banned',
      riskLevel: 'catastrophic',
      charlieTrust: 0,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Commander of the Exorcist army. Conducts annual purge of sinners. Aggressive, highly hostile to the concept of sinner redemption.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E01, S1E08',
      spoilerLevel: 'season_1',
      description: 'Commander of the exorcist forces during Season 1. His post-finale status is projected without rewriting the saved profile.',
      timelineStates: {
        season_1_start: { role: 'antagonist', status: 'banned', riskLevel: 'catastrophic' },
        season_1_end: { role: 'external', status: 'deceased', riskLevel: 'low' },
        season_2: { role: 'external', status: 'deceased', riskLevel: 'low' }
      }
    },
    {
      id: 'emily',
      name: 'Emily',
      alias: 'Seraphim Emily',
      type: 'angel',
      rank: 'seraph',
      role: 'ally',
      status: 'external',
      riskLevel: 'medium',
      charlieTrust: 85,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Younger Seraph of Heaven. Open-minded. Genuinely interested in checking if redemption is possible. Resists standard extermination policy.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E06',
      spoilerLevel: 'season_1',
      description: 'A high-ranking celestial Seraph who supports administrative transparency and the investigation of soul redemption.'
    },
    {
      id: 'sera',
      name: 'Sera',
      alias: 'High Seraphim',
      type: 'angel',
      rank: 'seraph',
      role: 'external',
      status: 'external',
      riskLevel: 'high',
      charlieTrust: 40,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'High Seraph of Heaven. Authorized the Exorcist purges to prevent potential uprising. Fears chaotic expansion of Hellbound populations.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E06',
      spoilerLevel: 'season_1',
      description: 'The senior Seraph of Heaven responsible for defensive policies and authorization of military operations in Hell.'
    },
    {
      id: 'lute',
      name: 'Lute',
      alias: 'Exorcist Lieutenant',
      type: 'angel',
      rank: 'exorcist',
      role: 'antagonist',
      status: 'external',
      riskLevel: 'high',
      charlieTrust: 0,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Season 1 exorcist officer. Operational threat values are simulation data.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E01, S1E08',
      spoilerLevel: 'season_1',
      description: 'An exorcist officer serving under Adam during the Season 1 conflict.'
    },
    {
      id: 'carmilla',
      name: 'Carmilla Carmine',
      alias: 'Arms Dealer',
      type: 'sinner',
      rank: 'overlord',
      role: 'ally',
      status: 'external',
      riskLevel: 'catastrophic',
      charlieTrust: 45,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Overlord and weapons dealer. Alliance and risk ratings are operational estimates.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E03, S1E07',
      spoilerLevel: 'season_1',
      description: 'An Overlord whose knowledge of angelic weapons becomes strategically important before the Season 1 finale.'
    },
    {
      id: 'rosie',
      name: 'Rosie',
      alias: 'Cannibal Town Overlord',
      type: 'unknown',
      rank: 'overlord',
      role: 'ally',
      status: 'external',
      riskLevel: 'high',
      charlieTrust: 65,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Her Overlord rank is shown; this registry does not invent an unconfirmed species classification.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E07',
      spoilerLevel: 'season_1',
      description: 'The Overlord associated with Cannibal Town who helps Charlie rally support before the finale.'
    },
    {
      id: 'zestial',
      name: 'Zestial',
      alias: 'Ancient Overlord',
      type: 'unknown',
      rank: 'overlord',
      role: 'external',
      status: 'external',
      riskLevel: 'catastrophic',
      charlieTrust: 20,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'The series confirms his Overlord standing, not a precise species taxonomy.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E03',
      spoilerLevel: 'season_1',
      description: 'A senior Overlord who participates in Carmilla Carmine\'s meeting of Hell\'s power holders.'
    },
    {
      id: 'zeezi',
      name: 'Zeezi',
      alias: 'Overlord Zeezi',
      type: 'unknown',
      rank: 'overlord',
      role: 'external',
      status: 'external',
      riskLevel: 'high',
      charlieTrust: 20,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Named in the official Season 2 cast; exact species remains unasserted here.',
      canonStatus: 'canon',
      timelineScope: 'season_1_start',
      sourceRef: 'S1E03',
      spoilerLevel: 'season_1',
      description: 'An Overlord seen among Hell\'s power holders during Season 1.'
    },
    {
      id: 'baxter',
      name: 'Baxter',
      alias: 'Inventor',
      type: 'sinner',
      rank: 'none',
      role: 'resident',
      status: 'resident',
      riskLevel: 'medium',
      charlieTrust: 35,
      rehabProgress: 5,
      rehabTracked: true,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Season 2 resident metrics are simulation values and must not be treated as episode facts.',
      canonStatus: 'canon',
      timelineScope: 'season_2',
      sourceRef: 'S2E01',
      spoilerLevel: 'season_2',
      description: 'A technically minded sinner introduced among the Season 2 hotel intake.'
    },
    {
      id: 'abel',
      name: 'Abel',
      alias: 'Abel',
      type: 'angel',
      rank: 'unknown',
      role: 'external',
      status: 'external',
      riskLevel: 'medium',
      charlieTrust: 0,
      rehabProgress: 0,
      rehabTracked: false,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Officially named in the Season 2 cast. Rank and operational authority are intentionally left unasserted.',
      canonStatus: 'canon',
      timelineScope: 'season_2',
      sourceRef: 'S2E02',
      spoilerLevel: 'season_2',
      description: 'A celestial Season 2 character confirmed by Prime Video\'s official cast listing.'
    },
    {
      id: 'sim_applicant_marlow',
      name: 'Marlow Glass',
      alias: 'Guarded Applicant',
      type: 'sinner',
      rank: 'none',
      role: 'resident',
      status: 'applicant',
      riskLevel: 'medium',
      charlieTrust: 20,
      rehabProgress: 30,
      rehabTracked: true,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Non-canon Simulation AU starter applicant for testing safety, consent, and trust-building plans with new residents.',
      canonStatus: 'simulation_au',
      timelineScope: 'season_1_start',
      sourceRef: '',
      spoilerLevel: 'none',
      description: 'A generic, non-canon hotel applicant who needs a safety-first intake and a resident-chosen support plan.'
    },
    {
      id: 'sim_applicant_ember',
      name: 'Ember Vale',
      alias: 'Restless Applicant',
      type: 'sinner',
      rank: 'none',
      role: 'resident',
      status: 'applicant',
      riskLevel: 'medium',
      charlieTrust: 25,
      rehabProgress: 30,
      rehabTracked: true,
      operationalDataStatus: 'simulation_au',
      contracts: [],
      notes: 'Non-canon Simulation AU starter applicant for testing coping rehearsal, restorative repair, and community contribution plans.',
      canonStatus: 'simulation_au',
      timelineScope: 'season_1_start',
      sourceRef: '',
      spoilerLevel: 'none',
      description: 'A generic, non-canon hotel applicant balancing impulsive coping patterns with a desire to contribute safely.'
    }
  ];

  const rooms: Room[] = [
    {
      number: '101',
      floor: 1,
      type: 'standard',
      occupantId: 'angeldust',
      capacity: 1,
      status: 'messy',
      dangerLevel: 'high',
      restrictions: ['no_substances', 'curfew_10pm'],
      maintenanceNotes: 'Requires regular cleanup. Traces of pink web patterns found on fixtures.',
      repairCost: 0,
      lastInspectionDate: '2026-06-25',
      lastInspectedBy: 'niffty'
    },
    {
      number: '102',
      floor: 1,
      type: 'standard',
      occupantId: null,
      capacity: 2,
      status: 'clean',
      dangerLevel: 'low',
      restrictions: [],
      maintenanceNotes: 'Freshly swept. Standard utilities functional.',
      repairCost: 0,
      lastInspectionDate: '2026-06-28',
      lastInspectedBy: 'niffty'
    },
    {
      number: '201',
      floor: 2,
      type: 'suite',
      occupantId: 'charlie',
      occupantIds: ['charlie', 'vaggie'],
      capacity: 2,
      status: 'clean',
      dangerLevel: 'low',
      restrictions: ['staff_only'],
      maintenanceNotes: 'Shared private suite for Charlie and Vaggie. The legacy occupantId stores Charlie as the primary reference.',
      repairCost: 0,
      lastInspectionDate: '2026-06-28',
      lastInspectedBy: 'vaggie'
    },
    {
      number: '202',
      floor: 2,
      type: 'secured_room',
      occupantId: 'alastor',
      capacity: 1,
      status: 'cursed',
      dangerLevel: 'catastrophic',
      restrictions: ['restricted_access', 'magical_interference_warning'],
      maintenanceNotes: 'Shadows seem to shift independently. Distant radio static emitted from shadows.',
      repairCost: 0,
      lastInspectionDate: '2026-06-20',
      lastInspectedBy: 'niffty'
    },
    {
      number: '301',
      floor: 3,
      type: 'staff_room',
      occupantId: null,
      capacity: 1,
      status: 'clean',
      dangerLevel: 'low',
      restrictions: ['staff_only'],
      maintenanceNotes: 'Administrative office. Not a second bedroom for Charlie.',
      repairCost: 0,
      lastInspectionDate: '2026-06-29',
      lastInspectedBy: 'charlie'
    },
    {
      number: '001',
      floor: 0,
      type: 'standard',
      occupantId: 'husk',
      capacity: 1,
      status: 'messy',
      dangerLevel: 'medium',
      restrictions: ['no_cheating_cards'],
      maintenanceNotes: 'Smells of cheap alcohol and tobacco. Playing cards scattered on desk.',
      repairCost: 0,
      lastInspectionDate: '2026-06-26',
      lastInspectedBy: 'niffty'
    },
    {
      number: '002',
      floor: 0,
      type: 'staff_room',
      occupantId: 'niffty',
      capacity: 1,
      status: 'clean',
      dangerLevel: 'low',
      restrictions: [],
      maintenanceNotes: 'Extremely clean. Under-bed storage full of taxidermy bugs.',
      repairCost: 0,
      lastInspectionDate: '2026-06-29',
      lastInspectedBy: 'niffty'
    },
    {
      number: '404',
      floor: 4,
      type: 'damaged_room',
      occupantId: null,
      capacity: 1,
      status: 'damaged',
      dangerLevel: 'high',
      restrictions: ['no_entry'],
      maintenanceNotes: 'Wall breached by local turf war artillery. Structural integrity compromised.',
      repairCost: 850,
      lastInspectionDate: '2026-06-24',
      lastInspectedBy: 'vaggie'
    }
  ];

  const factions: Faction[] = [
    { id: 'hotel', name: 'Hazbin Hotel', description: 'The rehabilitation initiative led by Charlie Morningstar.', influence: 15 },
    { id: 'heaven', name: 'Heavenly Seraphim', description: 'The ruling celestial administration of Heaven.', influence: 90 },
    { id: 'exorcists', name: 'Exorcist Army', description: 'Heavenly force responsible for the yearly exterminations in Hell.', influence: 80 },
    { id: 'vees', name: 'The Vees', description: 'Overlord media/tech cartel consisting of Vox, Valentino, and Velvette.', influence: 75 },
    { id: 'overlords', name: 'Independent Overlords', description: 'Feudal soul merchants ruling territory in the Pentagram.', influence: 65 },
    { id: 'morningstar', name: 'Morningstar Royalty', description: 'The ruling sovereign household of Hell.', influence: 95 }
  ];

  const relationships: Relationship[] = [
    { id: 'r1', charAId: 'charlie', charBId: 'vaggie', type: 'romantic', notes: 'Committed partners. Vaggie acts as protector; Charlie provides the vision.' },
    { id: 'r2', charAId: 'charlie', charBId: 'lucifer', type: 'family', notes: 'Father and daughter. Deep care but long emotional distance.' },
    { id: 'r3', charAId: 'angeldust', charBId: 'valentino', type: 'contract_bound', notes: 'Abusive soul contract binding Angel Dust to Valentino\'s studio work.' },
    { id: 'r4', charAId: 'husk', charBId: 'alastor', type: 'contract_bound', notes: 'Husk\'s soul is owned by Alastor, forcing his service at the bar.' },
    { id: 'r5', charAId: 'niffty', charBId: 'alastor', type: 'staff', notes: 'Alastor summons Niffty to help at the hotel; no on-screen soul-ownership contract is confirmed.' },
    { id: 'r6', charAId: 'angeldust', charBId: 'husk', type: 'ally', notes: 'Growing mutual trust. Husk understands the burden of binding contracts.' },
    { id: 'r7', charAId: 'angeldust', charBId: 'cherribomb', type: 'ally', notes: 'Close personal friends. Frequently engage in chaotic recreational activities.' },
    { id: 'r8', charAId: 'vox', charBId: 'alastor', type: 'enemy', notes: 'Rivalry between traditional broadcasting and modern network media.' },
    { id: 'r9', charAId: 'vox', charBId: 'valentino', type: 'romantic', notes: 'Allies within the Vees cartel with volatile personal dynamics.' },
    { id: 'r10', charAId: 'velvette', charBId: 'vox', type: 'ally', notes: 'Coordinated members of the Vees media empire.' }
  ];

  const rehabilitationPlans: RehabilitationPlan[] = [
    {
      id: 'plan_angeldust',
      characterId: 'angeldust',
      goals: ['De-escalate defense mechanisms', 'Establish boundary setting at work', 'Reduce consumption of chaotic substances'],
      obstacles: ['Coercive studio owner', 'Fear of vulnerability', 'Peer pressure from street turf wars'],
      triggers: ['Contact with Valentino', 'Feelings of isolation', 'Public media criticism'],
      empathyScore: 40,
      accountabilityScore: 30,
      impulseControlScore: 25,
      cooperationScore: 60,
      charlieNotes: 'He wants to improve, but his external environment keeps dragging him down. Empathy workshops are showing minor progress.',
      vaggieNotes: 'High liability but he respects the house rules when sober. Security must remain alert when he leaves for work.',
      staffPrivateNotes: 'Contracts with Valentino severely restrict his schedule, inducing heavy stress that triggers relapse.',
      isRedeemedConfirmed: false
    },
    {
      id: 'plan_sirpentious',
      characterId: 'sirpentious',
      goals: ['Cease aggressive territory invasions', 'Develop collaborative engineering skills', 'Acknowledge mistakes to fellow residents'],
      obstacles: ['Overwhelming need to fit in with Overlords', 'Paranoia regarding double-agents'],
      triggers: ['Criticism of his machinery', 'Insecurity about his social standing'],
      empathyScore: 35,
      accountabilityScore: 40,
      impulseControlScore: 45,
      cooperationScore: 50,
      charlieNotes: 'He is eager to please! His dramatic villain persona is just cover for loneliness.',
      vaggieNotes: 'Keep his weapons workshop under surveillance. Let Husk keep an eye on him in the game room.',
      staffPrivateNotes: 'Prone to spying for the Vees out of intimidation, but exhibits genuine remorse.',
      isRedeemedConfirmed: false
    },
    {
      id: 'plan_sim_applicant_marlow',
      characterId: 'sim_applicant_marlow',
      goals: ['Name two resident-chosen safety boundaries', 'Build a voluntary support contact plan', 'Complete one trust-building check-in'],
      obstacles: ['Low trust in institutions', 'Hypervigilance during group activities'],
      triggers: ['Unexpected physical proximity', 'Loss of control over a conversation'],
      empathyScore: 30,
      accountabilityScore: 30,
      impulseControlScore: 30,
      cooperationScore: 30,
      charlieNotes: 'Simulation AU starter plan. Begin with consent, predictable choices, and resident-defined safety.',
      vaggieNotes: 'Announce security procedures before acting and preserve a clear exit route.',
      staffPrivateNotes: 'Do not frame survival responses as wrongdoing. Record only voluntary goals.',
      isRedeemedConfirmed: false
    },
    {
      id: 'plan_sim_applicant_ember',
      characterId: 'sim_applicant_ember',
      goals: ['Rehearse a coping plan for escalating stress', 'Repair one specific harm after consent from the affected person', 'Choose a bounded hotel contribution'],
      obstacles: ['Impulsive conflict responses', 'Difficulty sustaining routines'],
      triggers: ['Public embarrassment', 'Unstructured high-pressure tasks'],
      empathyScore: 30,
      accountabilityScore: 30,
      impulseControlScore: 30,
      cooperationScore: 30,
      charlieNotes: 'Simulation AU starter plan. Separate harm experienced from harm chosen, and keep repair specific and consensual.',
      vaggieNotes: 'Use short duties, written expectations, and a stop condition agreed before each activity.',
      staffPrivateNotes: 'Track coping rehearsal and restorative repair as distinct approaches.',
      isRedeemedConfirmed: false
    }
  ];

  const rehabilitationSessions: RehabilitationSession[] = [
    {
      id: 's1',
      planId: 'plan_angeldust',
      date: '2026-06-27',
      type: 'empathy_workshop',
      summary: 'Participated in non-violent communication session. Exhibited dry humor but protected a newer sinner during roleplay.',
      empathyDelta: 5,
      accountabilityDelta: 2,
      impulseControlDelta: 0,
      cooperationDelta: 4,
      conductedBy: 'charlie'
    },
    {
      id: 's2',
      planId: 'plan_angeldust',
      date: '2026-06-28',
      type: 'therapy_like_checkin',
      summary: 'Post-shift safety check-in at the bar. Husk affirmed that the abuse was not Angel\'s fault and documented only resident-chosen support steps.',
      empathyDelta: 0,
      accountabilityDelta: 0,
      impulseControlDelta: 2,
      cooperationDelta: 5,
      conductedBy: 'husk'
    }
  ];

  const incidents: Incident[] = [
    {
      id: 'inc1',
      date: '2026-06-23',
      location: 'Lobby Entrance',
      residentsInvolved: ['sirpentious', 'cherribomb'],
      type: 'property_damage',
      severity: 'medium',
      summary: 'Sir Pentious attempted an assault using a steam-powered drilling tank. Cherri Bomb countered with explosive munitions.',
      consequences: 'Severe damage to the front wall, debris littered across the lobby, broken glass.',
      repairCost: 350,
      reputationImpact: -5,
      trustImpact: -10,
      actionTaken: 'Attack repelled by Vaggie and Cherri Bomb. Sir Pentious retreated. Reconstruction scheduled.',
      status: 'resolved',
      loreLink: 'lore_turf_war',
      tags: ['turf_war', 'property_damage']
    },
    {
      id: 'inc2',
      date: '2026-06-27',
      location: 'Studio District (External)',
      residentsInvolved: ['angeldust', 'valentino'],
      type: 'relapse',
      severity: 'high',
      summary: 'Angel Dust experienced a high-stress workplace conflict resulting in chemical relapse post-shift.',
      consequences: 'Absent from scheduled morning rehabilitation workshop. Heavy exhaustion.',
      repairCost: 0,
      reputationImpact: -2,
      trustImpact: -5,
      actionTaken: 'Brought back to hotel by Husk. Placed under 24h rest schedule. Empathy check-in scheduled.',
      status: 'contained',
      loreLink: 'lore_val_contract',
      tags: ['relapse', 'workplace_stress']
    }
  ];

  const staffTasks: StaffTask[] = [
    {
      id: 't1',
      date: '2026-06-29',
      title: 'Inspect First Floor Rooms',
      type: 'room_inspection',
      assignedTo: 'niffty',
      mentalWorkload: 2,
      status: 'pending',
      notes: 'Inspect for dust mites and minor structural cracks. Ensure standard safety locks are intact.'
    },
    {
      id: 't2',
      date: '2026-06-29',
      title: 'Review Security Perimeter',
      type: 'heaven_watch',
      assignedTo: 'vaggie',
      mentalWorkload: 5,
      status: 'in_progress',
      notes: 'Evaluate weapon stocks and structural integrity of the main gates before the next Purge countdown.'
    },
    {
      id: 't3',
      date: '2026-06-29',
      title: 'Resident Intake Interview',
      type: 'new_sinner_intake',
      assignedTo: 'charlie',
      mentalWorkload: 4,
      status: 'pending',
      notes: 'Prepare orientation packages and check trust metrics for incoming applicants.'
    }
  ];

  const reputation: ReputationState = {
    sinnerReputation: 15,
    redemptionCredibility: 5,
    internalTrust: 60,
    heavenAttention: 35,
    overlordHostility: 25,
    veesInfluence: 70,
    mediaChaos: 40
  };

  const timeline: TimelineState = {
    current: 'season_1_start',
    hideSpoilers: true,
    spoilerLevel: 'season_1',
    hotelState: 'original'
  };

  const loreCodex: LoreEntry[] = [
    {
      id: 'lore_hotel',
      title: 'Hazbin Hotel Initiative',
      entityName: 'Hazbin Hotel',
      category: 'location',
      description: 'A grand estate established in the Pride Ring of Hell to provide sanctuary and rehabilitation programs for sinners wishing to ascend to Heaven.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S1E01',
      spoilerLevel: 'none',
      timelineScope: 'season_1_start',
      isLocked: true
    },
    {
      id: 'lore_turf_war',
      title: 'Pilot-Era Turf Battle',
      entityName: 'Pride Ring Territory',
      category: 'event',
      description: 'The 2019 pilot depicts a turf battle involving Sir Pentious and Cherri Bomb. This record is isolated from Prime Video series canon unless an episode independently confirms a claim.',
      canonStatus: 'canon',
      sourceType: 'official_pilot',
      sourceRef: 'PILOT-2019',
      spoilerLevel: 'none',
      timelineScope: 'pilot_legacy',
      isLocked: true
    },
    {
      id: 'lore_val_contract',
      title: 'Valentino\'s Entertainment Contracts',
      entityName: 'Valentino',
      category: 'contract',
      description: 'Binding agreements that lease a sinner\'s soul and labor to Valentino\'s studios. Angel Dust is bound under a contract governing studio shifts.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S1E04',
      spoilerLevel: 'season_1',
      timelineScope: 'season_1_start',
      isLocked: true
    },
    {
      id: 'lore_purges',
      title: 'Annual Purge Protocol',
      entityName: 'Heaven Exorcists',
      category: 'world_rule',
      description: 'A yearly extermination in which exorcists descend into Hell. Season 1 later establishes Sera\'s authorization and the secrecy surrounding it.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S1E01, S1E06',
      spoilerLevel: 'season_1',
      timelineScope: 'season_1_start',
      isLocked: true
    },
    {
      id: 'lore_vaggie_origin',
      title: 'Vaggie\'s Exorcist Past',
      entityName: 'Vaggie',
      category: 'character',
      description: 'Vaggie is revealed to be a former exorcist who was left in Hell after sparing a sinner.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S1E06',
      spoilerLevel: 'season_1',
      timelineScope: 'season_1_start',
      isLocked: true
    },
    {
      id: 'lore_angelic_steel',
      title: 'Angelic Steel Can Kill Exorcists',
      entityName: 'Angelic Weapons',
      category: 'world_rule',
      description: 'Season 1 establishes that exorcists can be killed with angelic weaponry, a fact central to the hotel\'s defense plan.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S1E03, S1E07',
      spoilerLevel: 'season_1',
      timelineScope: 'season_1_start',
      isLocked: true
    },
    {
      id: 'lore_s1_final_battle',
      title: 'Battle at the Hotel',
      entityName: 'Hazbin Hotel',
      category: 'event',
      description: 'The Season 1 finale brings the exorcist forces into direct conflict with the hotel and its allies.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S1E08',
      spoilerLevel: 'season_1',
      timelineScope: 'season_1_end',
      isLocked: true
    },
    {
      id: 'lore_pentious_redeemed',
      title: 'First Demonstrated Sinner Redemption',
      entityName: 'Sir Pentious',
      category: 'event',
      description: 'After sacrificing himself in the finale, Sir Pentious appears in Heaven as a redeemed soul, demonstrating that redemption is possible.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S1E08',
      spoilerLevel: 'season_1',
      timelineScope: 'season_1_end',
      isLocked: true
    },
    {
      id: 'lore_adam_death',
      title: 'Adam\'s Death',
      entityName: 'Adam',
      category: 'event',
      description: 'Adam is killed during the Season 1 finale. He must not remain an active threat in post-finale timeline projections.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S1E08',
      spoilerLevel: 'season_1',
      timelineScope: 'season_1_end',
      isLocked: true
    },
    {
      id: 'lore_hotel_rebuilt',
      title: 'Finale Reconstruction',
      entityName: 'Hazbin Hotel',
      category: 'location',
      description: 'The original hotel is destroyed in the battle and a replacement is completed during the finale\'s closing reconstruction.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S1E08',
      spoilerLevel: 'season_1',
      timelineScope: 'season_1_end',
      isLocked: true
    },
    {
      id: 'lore_s2_new_intake',
      title: 'Season 2 Intake Surge',
      entityName: 'Hazbin Hotel',
      category: 'event',
      description: 'After the victory against Heaven, sinners flock to the rebuilt hotel, while Charlie must determine whether they seek redemption or revenge.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S2E01',
      spoilerLevel: 'season_2',
      timelineScope: 'season_2',
      isLocked: true
    },
    {
      id: 'lore_s2_pentious_heaven',
      title: 'Heaven Reacts to Pentious',
      entityName: 'Sir Pentious',
      category: 'event',
      description: 'Sir Pentious\' redemption creates upheaval in Heaven and is not welcomed by every celestial faction.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S2E02',
      spoilerLevel: 'season_2',
      timelineScope: 'season_2',
      isLocked: true
    },
    {
      id: 'lore_s2_vox_campaign',
      title: 'Vox Escalates Against Heaven',
      entityName: 'Vox and the Vees',
      category: 'threat',
      description: 'Vox exploits Hell\'s instability, rallies support and leads Overlords toward conflict with Heaven.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S2E01, S2E06',
      spoilerLevel: 'season_2',
      timelineScope: 'season_2',
      isLocked: true
    },
    {
      id: 'lore_s2_weapon_warning',
      title: 'Vox\'s Ultimatum',
      entityName: 'Vox',
      category: 'threat',
      description: 'Vox unveils a secret weapon and issues Heaven a final warning as the Season 2 conflict reaches its climax.',
      canonStatus: 'canon',
      sourceType: 'episode',
      sourceRef: 'S2E07',
      spoilerLevel: 'season_2',
      timelineScope: 'season_2',
      isLocked: true
    },
    {
      id: 'lore_simulation_boundary',
      title: 'Hotel Operations Are an AU Simulation',
      entityName: 'Manager Save',
      category: 'world_rule',
      description: 'Room numbers, budgets, risk ratings, trust percentages, schedules and rehabilitation scores are gameplay simulation data. They are not claims made by the series.',
      canonStatus: 'simulation_au',
      sourceType: 'user_manual_note',
      sourceRef: '',
      spoilerLevel: 'none',
      timelineScope: 'custom',
      isLocked: true
    }
  ];

  const resourceLedger: ResourceLedger[] = [
    { id: 'res1', date: '2026-06-01', type: 'income', category: 'donation', amount: 5000, description: 'Royal stipend allocation from the Morningstar Household.' },
    { id: 'res2', date: '2026-06-24', type: 'expense', category: 'repair', amount: 350, description: 'Purchased bricks and mortar for repairing lobby wall damages from incident #inc1.' },
    { id: 'res3', date: '2026-06-25', type: 'expense', category: 'bar_stock', amount: 200, description: 'Restocked whiskey and generic card decks for Husk\'s bar area.' },
    { id: 'res4', date: '2026-06-28', type: 'expense', category: 'cleaning_supplies', amount: 80, description: 'Detergents, industrial disinfectants, and replacement brooms for Niffty.' }
  ];

  const auditLogs: AuditLog[] = [
    { id: 'log1', timestamp: '2026-06-29T00:00:00Z', action: 'DATABASE_INITIALIZATION', details: 'Seed database loaded successfully with baseline Hazbin lore and characters.' }
  ];

  const settings: AppSettings = {
    appName: 'Hellbound Hotel Manager',
    randomEventsEnabled: true,
    theme: 'default-artdeco'
  };

  return {
    characters,
    rooms,
    rehabilitationPlans,
    rehabilitationSessions,
    incidents,
    staffTasks,
    reputation,
    timeline,
    loreCodex,
    factions,
    relationships,
    resourceLedger,
    auditLogs,
    settings,
    extensions: {}
  };
}
